gym_project/gym_app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register , name='register'),
    path('login/', views.user_login, name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('admin/', admin.site.urls),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
]

gym_project/gym_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gym_app.urls')),
    path('gym_trainer/', include(('gym_trainer.urls', 'gym_trainer'), namespace='gym_trainer')),
]

gym_project/gym_trainer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    path('exercise/list', views.exercise_list, name='exercise_list'),
    path('exercise/create', views.exercise_create, name='exercise_create'),
    path('exercise/edit/<int:exercise_id>', views.exercise_edit, name='exercise_edit'),
    path('routine/list', views.routine_list, name='routine_list'),
    path('routine/create', views.routine_create, name='routine_create'),
    # path('routine/edit/<int:routine_id>', views.routine_edit, name='routine_edit'),
    # path('routine/delete/<int:routine_id>', views.routine_delete, name='routine_delete'),
]

gym_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Gym App{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'dist/bundle.css' %}">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">Gimnàs App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% if active_tab == 'home' %}active{% endif %}"
                                href="{% url 'home' %}">Inici</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown">
                                {{ user.username }}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li>
                                    <a class="dropdown-item {% if active_tab == 'profile' %}active{% endif %}"
                                        href="{% url 'profile_edit' %}">
                                        Editar Perfil
                                    </a>
                                </li>
                                {% if user.role == "trainer" %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'gym_trainer:exercise_list' %}">Exercisis</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'gym_trainer:routine_list' %}">Rutines</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="">Horari</a>
                                </li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Tancar Sessió</a>
                                </li>
                            </ul>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Iniciar Sessió</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">Registrar-se</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        {% if messages %}
        <br>
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
    </div>

    <main class="container py-4">
        {% block content %}
        {% endblock %}
    </main>
    <script src="{% static 'dist/bundle.js' %}"></script>
</body>

</html>