gym_project/gym_app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register , name='register'),
    path('login/', views.user_login, name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('admin/', admin.site.urls),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
]

gym_project/gym_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gym_app.urls')),
    path('gym_trainer/', include(('gym_trainer.urls', 'gym_trainer'), namespace='gym_trainer')),
]

gym_project/gym_trainer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    path('exercise/list', views.exercise_list, name='exercise_list'),
    path('exercise/create', views.exercise_create, name='exercise_create'),
    path('exercise/edit/<int:exercise_id>', views.exercise_edit, name='exercise_edit'),
    path('routine/list', views.routine_list, name='routine_list'),
    path('routine/create', views.routine_create, name='routine_create'),
    # path('routine/edit/<int:routine_id>', views.routine_edit, name='routine_edit'),
    # path('routine/delete/<int:routine_id>', views.routine_delete, name='routine_delete'),
]

gym_project/gym_trainer/models.py
from django.db import models
from django.conf import settings

class Exercise(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    
    
    def __str__(self):
        return self.name
    
    class Meta:
        # ordering = ['-id']
        db_table = 'exercises'
    
class Routine(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    trainer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='routines')
    exercises = models.ManyToManyField(Exercise, related_name='routines')

    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        # ordering = ['-created_at']
        db_table = 'routines'

class Schedule(models.Model):
    id = models.AutoField(primary_key=True)
    routine = models.ForeignKey(Routine, on_delete=models.CASCADE, related_name='schedules')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='schedules')
    hour = models.TimeField()

    class Meta:
        # ordering = ['-date', '-time']
        db_table = 'schedules'

gym_project/gym_trainer/forms.py
from django import forms
from .models import Exercise, Routine
from djongo import models
from bson import ObjectId

class ExerciseForm(forms.ModelForm):
    class Meta:
        model = Exercise
        fields = ['name', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
        }

class RoutineForm(forms.ModelForm):
    exercises = forms.ModelMultipleChoiceField(
        queryset=Exercise.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    class Meta:
        model = Routine
        fields = ['name', 'description', 'exercises']

gym_project/gym_trainer/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import ExerciseForm, RoutineForm
from .models import Exercise, Routine
from bson import ObjectId
from djongo import models
from django.shortcuts import get_object_or_404

# Create your views here.

def is_trainer(user):
    return user.role == "trainer"


@user_passes_test(is_trainer)
@login_required
def exercise_list(request):
    exercises = Exercise.objects.all()
    return render(request, 'gym_trainer/exercise_list.html', {'exercises': exercises})

@user_passes_test(is_trainer)
@login_required
def exercise_create(request):
    if request.method == 'POST':
        form = ExerciseForm(request.POST)
        if form.is_valid():
            exercise = form.save
            return redirect('exercise_list')
    else:
        form = ExerciseForm()
    return render(request, 'gym_trainer/exercise_create_edit.html', {'form': form})

@user_passes_test(is_trainer)
@login_required
def exercise_edit(request, exercise_id=None):
    if exercise_id:  # Si se proporciona un ID, significa que estamos editando un ejercicio existente
        exercise = get_object_or_404(Exercise, id=exercise_id)
    else:  # Si no hay ID, estamos creando un ejercicio nuevo
        exercise = None

    if request.method == 'POST':
        form = ExerciseForm(request.POST, instance=exercise)
        if form.is_valid():
            form.save()
            return redirect('gym_trainer:exercise_list')  # Redirigir a la lista de ejercicios tras guardar
    else:
        form = ExerciseForm(instance=exercise)  # Mostrar formulario vacío o prellenado con datos del ejercicio

    return render(request, 'gym_trainer/exercise_create_edit.html', {'form': form, 'exercise': exercise})

@user_passes_test(is_trainer)
@login_required
def routine_list(request):
    routines = Routine.objects.all()
    return render(request, 'gym_trainer/routine_list.html', {'routines': routines})

@user_passes_test(is_trainer)
@login_required
def routine_create(request):
    exercises = Exercise.objects.all()
    if request.method == 'POST':
        form = RoutineForm(request.POST)
        if form.is_valid():
            routine = form.save
            return redirect('gym_trainer:routine_list')
    else:
        form = RoutineForm()
    return render(request, 'gym_trainer/routine_create_edit.html', {'form':form} )

gym_project/gym_trainer/templates/gym_trainer/exercise_create_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>{% if exercise %}Editar{% else %}Crear{% endif %} Exercisi</h1>
    
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}" class="form-label">
                {{ field.label }}
            </label><br>
            {{ field.errors }}
            {{ field }}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary mt-3">{% if exercise %}Guardar{% else %}Crear{% endif %} Exercisi</button>
        
        <a href="{% url 'gym_trainer:exercise_list' %}" class="btn btn-secondary mt-3">Cancelar</a>
    </form>
</div>
{% endblock %}

gym_project/gym_trainer/templates/gym_trainer/exercise_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Llista d'Exercici</h1>
    
    <!-- Formulario para crear/editar rutina -->
    <form method="post">
        {% csrf_token %}
        
        <!-- Campos de la rutina -->
        {{ form.exercise}}
        
        <!-- Lista de ejercicios disponibles -->
        <a href="{% url 'gym_trainer:exercise_create' %}" class="btn btn-secondary mt-3">Crear Exercici</a>
        <div class="form-group">
            {% for exercise in exercises %}
                <div>
                    <label><a href="{% url 'gym_trainer:exercise_edit' exercise.id%}">{{ exercise.name }}</a></label> 
                </div>
            {% endfor %}
        </div>
    </form>
</div>
{% endblock %}

gym_project/gym_trainer/templates/gym_trainer/routine_create_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>{% if exercise %}Editar{% else %}Crear{% endif %} Rutina</h1>
    
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary mt-3">{% if exercise %}Guardar{% else %}Crear{% endif %} Rutina</button>
        
        <a href="{% url 'gym_trainer:routine_list' %}" class="btn btn-secondary mt-3">Cancelar</a>
    </form>
</div>
{% endblock %}

gym_project/gym_trainer/templates/gym_trainer/routine_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Llista de Rutines</h1>
    
    <!-- Formulario para crear/editar rutina -->
    <form method="post">
        {% csrf_token %}
        
        <!-- Campos de la rutina -->
        {{ form.routines}}
        
        <!-- Lista de ejercicios disponibles -->
        <a href="{% url 'gym_trainer:routine_create' %}" class="btn btn-secondary mt-3">Crear Rutina</a>
        <div class="form-group">
            {% for routine in routines %}
                <div>
                    <label><a href="{% url 'gym_trainer:exercise_edit' routine.id%}">{{ routine.name }}</a></label> 
                </div>
            {% endfor %}
        </div>
    </form>
</div>
{% endblock %}